Random Seed: 123
train: Epoch: 0	
loading annotations into memory...
Done (t=2.24s)
creating index...
index created!
WARNING: NO MODEL LOADED !!!
loading annotations into memory...
Done (t=1.99s)
creating index...
index created!
loading annotations into memory...
Done (t=2.07s)
creating index...
index created!
Traceback (most recent call last):
  File "train_net.py", line 86, in <module>
    main()
  File "train_net.py", line 77, in main
    train(cfg, network)
  File "train_net.py", line 51, in train
    trainer.train(epoch, train_loader, optimizer, recorder)
  File "/data0/zjw/PolySnake/lib/train/trainers/trainer.py", line 38, in train
    output, loss, loss_stats, image_stats = self.network(batch)
  File "/home/zjw/miniconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zjw/miniconda3/envs/snake/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 167, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/zjw/miniconda3/envs/snake/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 177, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/zjw/miniconda3/envs/snake/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/zjw/miniconda3/envs/snake/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/zjw/miniconda3/envs/snake/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/zjw/miniconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "lib/train/trainers/snake.py", line 24, in forward
    output = self.net(batch['inp'], batch)
  File "/home/zjw/miniconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/ct_snake.py", line 25, in forward
    output, cnn_feature = self.dla(x) # dla输出的output为ct_heatmap,point wh offset,boundry mask,这里输出的cnn_feature为x经过4倍降采样的(而且是经过多个尺度特征增强的，)
  File "/home/zjw/miniconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/dla.py", line 469, in forward
    x = self.base(x)
  File "/home/zjw/miniconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/dla.py", line 291, in forward
    x = getattr(self, 'level{}'.format(i))(x)
  File "/home/zjw/miniconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zjw/miniconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/zjw/miniconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zjw/miniconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 140, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "/home/zjw/miniconda3/envs/snake/lib/python3.7/site-packages/torch/nn/functional.py", line 2150, in batch_norm
    input, weight, bias, running_mean, running_var, training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 168.00 MiB (GPU 0; 11.76 GiB total capacity; 627.18 MiB already allocated; 94.69 MiB free; 660.00 MiB reserved in total by PyTorch)

